### ISSUE TITLE
Want to change Article "Emissions embedded in trade...." Figure 2: into dd chart(s)

### ISSUE THREAD

**Issue by peterfrenchons** [GSS-Cogs/ukstats.ccv2.theme#18]
Figure 2: UK total imports and exports of goods by aggregated product (SITC), 2020, (£ billions)
Climate Change team want to change this to a data driven visualisation to enable easy data driven updates in the future.

On current portal this is an image.

The task here to generate in v2.0 as data driven visualisation. 

Issue reported by Bec 19/07.

Note from Bec:
Figure 2 data is already on the datastore:
https://beta.gss-data.org.uk/cube/about?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-trade-in-goods-catalog-entry (and this should be the same data needed for Figure 3).

**Comment by Shannon95** [comment]
[Figure 2 Charts ](https://staging.climate-change.data.gov.uk/articles/emissions-embedded-in-trade-and-impacts-on-climate-change)(Imports and Exports) are now created with two separate charts, one above another due to the scaling of the long labels. 
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/55798687/188704717-14f8bd83-64f8-4627-a679-71e962eceb05.png">
- One aspect to note is the data is ascending instead of descending.
